#!/usr/bin/env bash
# Installs nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx start
