#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i '/^\tserver_name.*/a \\trewrite ^\/redirect_me https:\/\/osamabasheer.me permanent;' /etc/nginx/sites-available/default
sudo sed -i '/^\tserver_name.*/a \\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html/;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo service nginx restart
