#!/usr/bin/env bash
# Configure web-02 to be identical to web-01 and add a header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" >> "/var/www/html/index.html"
sudo echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i '/^\tserver_name.*/a \\trewrite ^\/redirect_me https:\/\/osamabasheer.me permanent;' /etc/nginx/sites-available/default
sudo sed -i '/^\tserver_name.*/a \\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html/;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo sed -i "25i add_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx reload
sudo service nginx restart
