#!/usr/bin/env bash
# Configure web-02 to be identical to web-01 and add a header
sudo apt-get -y update
sudo apt-get -y install nginx
mkdir -p /var/www/html
echo "Holberton School" >> "/var/www/html/index.html"
sudo echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i "25i add_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx reload
sudo service nginx restart
