#!/usr/bin/env bash
# sets up HAProxy(Load Balancing) servers
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i "9i ENABLED=1" /etc/default/haproxy
cat >> /etc/haproxy/haproxy.cfg
frontend domain
        mode http
        bind *:80
        default_backend servers

backend servers
        balance roundrobin
        server 838-web-01 34.73.247.215:80 check
        server 838-web-02 34.73.246.167:80 check
EOF

sudo service haproxy restart
