#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hours=0
min=1
while ((hours <= 12)); do
      echo Hour: $hours
      while ((min < 60)); do
      	        echo $min
		      min=$((min+1))
		      done
		      min=1
		      hours=$((hours+1))
done