#!/usr/bin/env bash
# Bash script that configs an Ubuntu server
cp /etc/hosts temp
sed -i "/localhost/s/127.0.0.1/127.0.0.2/" temp
sed -i "/localhost/a8.8.8.8\tfacebook.com" temp
cp -f temp /etc/hosts
