#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
pkill apache2
sudo chmod 0777 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
